config/routes.rb
Rails.application.routes.draw do

  resources :pages do
    resources :links
  end



  get '/:id', to: 'pages#show'
  
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/contact', to: 'static_pages#contact'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get "*path", to: redirect('/home')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :page
end

app/models/page.rb
class Page < ApplicationRecord

  has_many :links, dependent: :destroy

  belongs_to :user

  validates_length_of :banner_url, minimum: 11, maximum: 12, :allow_blank => true

  validates_format_of :banner_url,
   :with    => %r{\.(jpe?g|png)\z}i,
    :message => "Invalid image", :allow_blank => true

  validates_format_of :button_background_url,
   :with    => %r{\.(jpe?g|png)\z}i,
    :message => "Invalid image", :allow_blank => true
    
  validates_format_of :background_url,
   :with    => %r{\.(jpe?g|png)\z}i,
    :message => "Invalid image", :allow_blank => true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :page, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @page = Page.find(params[:page_id])
    @link = @page.links.new
    if current_user.page != @page && current_user.authorisation < 30
      redirect_to(root_path)
    end
  end

  # GET /links/1/edit
  def edit
    if current_user.page != @page && current_user.authorisation < 30
      redirect_to(root_path)
    end
  end

  # POST /links
  # POST /links.json
  def create
    @page = Page.find(params[:page_id])
    if current_user.page != @page && current_user.authorisation < 30
      redirect_to(root_path)
    end
    @link = @page.links.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @page, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to page_path(@page), notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @pahe }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to @page, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @page = Page.find(params[:page_id])
      @link = @page.links.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:name, :link,:slug)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  before_action only: [:edit,:new,:create] do
    redirect_back(fallback_location: root_path, alert: "You need to be signed in to create a page") unless user_signed_in?
  end
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page_visible = true
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
    if current_user.page != @page && current_user.authorisation < 30
      redirect_to(root_path)
    end
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = current_user.create_page(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    if current_user.page != @page && current_user.authorisation < 30
      redirect_to(root_path)
    end
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:bio, :banner_url, :background_url, :background_color, :button_background_url, :button_background_color, :ad_visible)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :authorisation, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_page_visible?
    !!@page_visible
  end


end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def valid_image?(img)
    img.length >= 11
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left" style="font-size:300%;">
        <% if user_signed_in? %>
          <% if current_user.page %>
            <li>
            <% if link_page_visible? && @page == current_user.page %>
              <%= link_to "Edit Page", edit_page_path(current_user.page) %>
            <% else %>
              <%= link_to "My Page", page_path(current_user.page) %>
            <% end %>
            </li>
          <% else %>
            <li class="<%= current_page?(new_page_path)? "active" : "" %>">
              <%= link_to "New Page", new_page_path %>
            </li>
          <% end %>
        <% end %>
        <li class="<%= current_page?(pages_path)? "active" : "" %>">
          <%= link_to "Pages", pages_path %>
        </li>
        <li><%= link_to 'Games', "https://play.google.com/store/apps/details?id=com.spartanfox.blocktoidz&hl=en"%></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "Spartanfox Productions", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right" style="font-size:200%;">
        <% if user_signed_in? %>
          <div style="color: #EEE;">
            Logged in as <strong><%= current_user.username %></strong>
          <div>
        <%end%>
      </ul>
    </nav>
  </div>
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left" style="font-size:300%;">

        <li class="<%= current_page?(home_path)? "active" : "" %>">
          <%#= link_to "Home", home_path %>
        </li>

        <% if user_signed_in? %>
          <% if current_user.page %>
            <li>
            <% if link_page_visible? && @page == current_user.page %>
              <%= link_to "Edit Page", edit_page_path(current_user.page) %>
            <% else %>
              <%= link_to "My Page", current_user.page %>
            <% end %>
            </li>
          <% else %>
            <li class="<%= current_page?(new_page_path)? "active" : "" %>">
              <%= link_to "New Page", new_page_path %>
            </li>
          <% end %>
        <% end %>
        <li class="<%= current_page?(pages_path)? "active" : "" %>">
          <%= link_to "Pages", pages_path %>
        </li>
        <li><%= link_to 'Games', "https://play.google.com/store/apps/details?id=com.spartanfox.blocktoidz&hl=en"%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" style="font-size:300%;">
        <%if user_signed_in?%>
          <li><%= link_to 'Edit profile', edit_user_registration_path%></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login"  , new_user_session_path      %></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head name="viewport" content="width=device-width, initial-scale=2">
    <title>Listedlinks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if link_page_visible? && valid_image?(@page.background_url) %>
    <body background="http://tinyimg.io/i/<%= @page.background_url %>">
  <% else %>
    <body>
  <% end %>
    <header class="navbar-fixed-top">
      <div class="container">
        <nav>
          <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
          <% end %>
        </nav>
      <div>
    </header >
    <big>
      <strong>
    <% unless link_page_visible? %>
      <%= render 'layouts/header' %>
      <div class="container" style="padding-top:10px">
        <div class="center jumbotron">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <div class="container" style="padding-top:10px">
          <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    <% end %>
  </strong>
  </big>
  </body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for [@page, @link], url: page_links_path  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :slug, collection: 0..10, selected: @link.slug, label: 'Priority (Links are sorted by largest numbers first)' %>
    <%= f.input :name, label: 'Link name' %>
    <%= f.input :link, label: 'Link URL' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-lg btn-primary"  %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>
<%= simple_form_for [@page, @link], url: page_link_path  do |f| %>
  <%= f.error_notification %>
  <h2>
    <div class="form-inputs">
      <%= f.input :slug, collection: 0..10, selected: @link.slug, label: 'Priority (Links are sorted by largest numbers first)' %>
      <%= f.input :name, label: 'Link name' %>
      <%= f.input :link, label: 'Link URL' %>
    </div>
  </h2>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-lg btn-primary"  %>
  </div>
<% end %>

<%= link_to 'Back', page_path(@page), class: "btn btn-lg btn-default"%>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', page_path(@page), class: "btn btn-lg btn-default"  %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <h2>
      <%= f.input :bio, input_html:{class:"input-lg"}%>
      <%= f.input :background_color, input_html:{class:"input-lg"}, label: 'Background color'%>

      <%= f.input :button_background_color, input_html:{class:"input-lg"}, label: 'Button background color' %>

      Upload an image to <%= link_to 'tinyimg', 'https://tinyimg.io/'%> then paste the image name in here for a custom background and buttons
      <%= f.input :banner_url           , label: 'Banner url'           , placeholder: 'aaaaaaa.jpg', input_html: { maxlength: 12, minlength: 11,class:"input-lg" } %>
      <%= f.input :background_url       , label: 'Background url'       , placeholder: 'aaaaaaa.jpg', input_html: { maxlength: 12, minlength: 11,class:"input-lg" }  %>
      <%#= f.input :button_background_url, label: 'Button background url', placeholder: 'aaaaaaa.jpg', input_html: { maxlength: 12, minlength: 11,class:"input-lg" } %>
      You can help support the website by allowing users to see my game
      <br>
      <br>
      Users who choose to keep this option on will be first on the list of pages as supporters
      <%= f.input :ad_visible, input_html:{class:"input-lg"}, label: 'Supporter' %>
    </h2>
  </div>
<br>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-lg btn-primary"  %>

  </div>
  <br>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page, class: "btn btn-lg btn-default" %>
<%= link_to 'Back', pages_path, class: "btn btn-lg btn-default"%>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h2>User pages</h2>
<ul class="list-group">
  <% @pages.where(ad_visible:true).each do |page| %>
    <li class="list-group-item">
      <h2>
        <%= link_to "#{page.user.username.pluralize} links" , page_path(page),
          class: "list-group-item list-group-item-action"
        %>
      </h2>

      <%if user_signed_in? && current_user.authorisation >= 30%>
        <tr>
          <td><%= link_to 'Show', page %></td>
          <td><%= link_to 'Edit', edit_page_path(page) %></td>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </li>
  <% end %>
</ul>
<br>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path, class: "btn btn-lg btn-default" %>

app/views/pages/show.html.erb
<center>
  <div class="center jumbotron">
    <% if valid_image?(@page.banner_url)%>
        <img src="http://tinyimg.io/i/<%= @page.banner_url %>" class="img-thumbnail" style="width:20%">
    <% end %>
    <h1><%=@page.user.username%></h1>
    <%=simple_format @page.bio, {}, wrapper_tag: 'h2'%>
    <% if @page.user == current_user || (user_signed_in? && current_user.authorisation >=30)%>
      <%= link_to 'Edit', edit_page_path(@page), class: "btn btn-lg btn-info" %>
      <%if @page.links.length<10%>
        <%= link_to 'Add link', new_page_link_path(@page), class: "btn btn-lg btn-info" %>
      <%end%>
      <br><br>
    <% end %>

    <% @page.links.sort_by {|l| [ -l.slug, l.created_at] }.each do |link| %>
      <div class="btn-group btn-group-lg btn-group-justified">
        <a href="<%= link.link %>" class="btn btn-primary btn-block">
          <%= link.name %>
        </a>
        <% if @page.user == current_user || (user_signed_in? && current_user.authorisation >=30)%>
          <%= link_to 'Edit link', edit_page_link_path(@page,link),class:"btn btn-info btn-block " %>
          <%= link_to 'Delete ', [@page,link],class:"btn btn-danger btn-block", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
      <br>
    <% end %>
    <% if @page.ad_visible %>
      <a href="https://play.google.com/store/apps/details?id=com.spartanfox.blocktoidz&hl=en" class="btn btn-primary btn-lg btn-block">Blocktoidz</a>
      <br>
    <% end %>
      </div>
  </center>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<center>
    <h1>Welcome to listed links</h1>
    <h2>This is a website dedicated to sharing multiple links with complete personalisation of your own free page!</h2>
    <h2>Checkout my free games on the
      <a href="https://play.google.com/store/apps/details?id=com.spartanfox.blocktoidz&amp;hl=en" class="btn btn-primary">
        Play Store
      </a>
    </h2>
    <%unless user_signed_in?%>
      <h2>to get started
        <%= link_to "Sign in", new_user_session_path     , class: "btn btn-default" %> or
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-default" %>
         and start customising!</h2>
    <%end%>
</center>